### ISSUE TITLE
Implement menu controller

### ISSUE THREAD

**Issue by vova-lantsov-dev** [krok-lives-matter/CaffeMenuBot_Back-End#9]
### Actions implementation (including validation)
- [x] Add category
- [x] Delete category by id
- [x] Update category
- [x] List all categories and dishes
- [x] Add dish to category using category id
- [x] Delete dish by id
- [x] Update dish
### Tests
- [x] Add category
- [x] Delete category by id
- [x] Update category
- [x] List all categories and dishes
- [x] Add dish to category using category id
- [x] Delete dish by id
- [x] Update dish

**Comment by EdvardPotapenko** [comment]
@luxoff Hi! **Please help with closing this issue.** 

I've started working on tests for menu Controller, but there is one catch that I can't quite work around yet. With our current seeding method ( that is commented in CaffeMenuBotApplicationFactory at Integration Tests at the moment) I get strange behavior: WebApplicationFactory gets instantiated twice, so the method that configures it (and seeds database) gets called twice too. That's a problem, because check for existing data in context performs simultaneously on 2 threads and always gets that context.Dishes.Any() (see DatabaseSeeder implementation for details),or whatever, are false (no data is there), resulting in duplicate data inside of a context and problem of retrieving it later.

With admin user seeding i've worked around this by performing user creation using OnModelCreation method in CaffeMenuBotContext (CaffeMenuBot.Data), maybe you should just seed other things there too, but that feels like a bad idea. Microsoft docs encouraging method that is used by us currently, but as you can see it won't work as expected.

If you can find a fix for that and write other tests for this controller - this would be great help. 

@vova-lantsov-dev I think we would need some help from you too, buddy. 

Thanks for your time guys, currently I'm feeling really not that good, so I'll do my best participating in project as I can. 

@illoria Sorry for not being able to attend today's meeting, hope you did alright without me.
